### ISSUE TITLE
add support for CloudLinux

### ISSUE THREAD

**Issue by sparvu** [chorny/Linux-Distribution#5]
Running on CloudLinux we see the following information missing:

    # get os, relos
    if(my $distro = $dl->distribution_name()) {
        if (defined($dl->distribution_version()) && ($dl->distribution_version()) ne "" ) {
            $relos = $dl->distribution_version();
        } else {
            $relos = "NA";
        }
        $os = $distro;
    }

 os=redhat
 relos=NA

This distro is unknown to Linux::Distribution:

Distributor ID:	CloudLinuxServer
Description:	CloudLinux Server release 5.11 (Vladislav Volkov)
Release:	5.11
Codename:	VladislavVolkov

Please add support for this one.

**Comment by chorny** [comment]
To add new Linux distribution, please send following files:
/etc/lsb-release
/etc/*-release
/etc/*_version

and output of:
uname -a
lsb_release

**Comment by sparvu** [comment]
See below:

* /etc/lsb-release, /etc_version - no such things

 * /etc/redhat-release
```
   [root@cl564 Linux]# cat /etc/redhat-release 
   CloudLinux Server release 5.11 (Vladislav Volkov)
```
 * uname -a

 ```
Linux cl564 2.6.18-471.3.1.el5.lve0.8.72 #1 SMP Wed Mar 12 18:22:20 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
 ```
 

 * lsb_release -a

 ```
[root@cl564 Linux]# lsb_release -a
LSB Version:	:core-4.0-amd64:core-4.0-ia32:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-ia32:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-ia32:printing-4.0-noarch
Distributor ID:	CloudLinuxServer
Description:	CloudLinux Server release 5.11 (Vladislav Volkov)
Release:	5.11
Codename:	VladislavVolkov

 ```

This is more or less a CentOS, or RHEL type of distro.

**Comment by chorny** [comment]
Sorry, \* symbols were eaten by markdown.

Are there any other /etc/\*-release or /etc/\*_version files?

**Comment by sparvu** [comment]
We have something like these:

```
[root@cl564 etc]# ls -lrt *-release
-rw-r--r-- 1 root root 50 Sep 19  2014 redhat-release
-rw-r--r-- 1 root root 50 Sep 19  2014 CloudLinux-release

[root@cl564 etc]# cat CloudLinux-release 
CloudLinux Server release 5.11 (Vladislav Volkov)
```

and no other *-version files.

**Comment by chorny** [comment]
added in 0.23

**Comment by sparvu** [comment]
thanks. I will test soon.

**Comment by sparvu** [comment]
ok CloudLinux 5.11 works fine. Thank you.

However on CloudLinux 6.x we see these:

```
1438257618:myserver:x86_64:NA:redhat:NA:Linux 2.6.32-458.23.2.lve1.2.48.el6.x86_64:1:8:32802092.00:2097144.00:12:2:NA:85d 14h 11m 23s
```

where, OS=redhat and release=NA. It seems it does not parse correctly the /etc configuration files.


Im posting here the CloudLinux 6.x config files:

```
# ls -lrt *-release
-rw-r--r-- 1 root root 152 Mar  6  2013 lsb-release
-rw-r--r-- 1 root root  45 Oct 19  2014 redhat-release
lrwxrwxrwx 1 root root  14 May  5 20:33 system-release -> redhat-release
```

 /etc/redhat-release

```
# cat /etc/redhat-release
CloudLinux Server release 6.6 (Leonid Kizim)
```

uname

```
Linux myserver 2.6.32-458.23.2.lve1.2.48.el6.x86_64 #1 SMP Fri Jan 3 11:26:27 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
```

lsb_release

```
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CloudLinuxServer
Description:	CloudLinux Server release 6.6 (Leonid Kizim)
Release:	6.6
Codename:	LeonidKizim
```
